### ISSUE TITLE
Additonal Backbones for Object Detection Task

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#119]
Object Detection task currently only seems to support FasterRCNN it would be good to have additional backbones such as RetinaNet or YoloV5 .

**Comment by zhiqwang** [comment]
Hi @aribornstein , I'm working on integrating YOLOv5 with Lightning [here](https://github.com/zhiqwang/yolov5-rt-stack), I am learning the interface of Lightning and flash, and hope I could help to add YOLOv5 to flash.

I am now open a [issue](https://github.com/zhiqwang/yolov5-rt-stack/issues/59) in my own repo to test the trainer and inference of Lightning. After this issue is done, I would like to submit a PR for the YOLOv5 task.

And this is my first attempt on Lightning and flash, if there is a problem with the handling, please point it out.

cc @tchaton

**Comment by aribornstein** [comment]
That's amazing news !!! Look forward to finally having a clean way of finetuning and comparing different object detectors on TPUs and Distributed Clusters.

**Comment by zhiqwang** [comment]
Hi @aribornstein 

I follow the development philosophy of torchvision's retinanet or faster-rcnn, and try to keep the same interface as torchvision. For the aspects of the YOLOv5 model itself, the work on the inference procedure in done, it can load a checkpoint trained by [**ultralytics**](https://github.com/ultralytics/yolov5), the inference result is also same as **ultralytics**.

On the training procedure, It can also be used for training, but I didn't train a model on the actual datasets (neither COCO nor VOC). The author of **ultralytics** added a lot of tricks to his trainer mechanism. I guess there is still some distance to train a model as good as **ultralytics**, I am still working on this.

**Comment by kaushikb11** [comment]
@aribornstein RetinaNet with other backbones added #121 :)
@zhiqwang That's great!

**Comment by edgarriba** [comment]
@zhiqwang what's the status on this. Do you have any progress ?

**Comment by zhiqwang** [comment]
Hi @edgarriba , I haven't completely solved the training problem ,( I hope I can resolve this problem before June.

**Comment by zhiqwang** [comment]
Hi, I postponed the DDL again.

I was a little busy with some other work and didn’t push this task forward. I’m now starting to come back to the development here. I'm very sorry that this affects your progress.

**Comment by aniketmaurya** [comment]
Hi, I have started working on YoloV5 integration with Flash.

**Comment by juliangrosshauser** [comment]
Integrating YOLOv5 into Lightning Flash would result in a license conflict, because [YOLOv5 is licensed under GPL-3.0](https://github.com/ultralytics/yolov5/blob/master/LICENSE) and [Lightning Flash under Apache 2.0](https://github.com/PyTorchLightning/lightning-flash/blob/master/LICENSE). In order to comply with the GPL-3.0 license you need to [disclose your source code](https://choosealicense.com/licenses/gpl-3.0), which means you wouldn't be able to use Lightning Flash in closed source projects anymore.

**Comment by ethanwharris** [comment]
@juliangrosshauser Presumably this would apply to copying the code only though right? Our intention here is simply to have yolov5 as a dependency which is fine no? E.g. we would be adding support for icevision, which lists yolov5 as a dependency and is itself licensed under Apache 2.0. Please correct me if I am mistaken :smiley:

**Comment by juliangrosshauser** [comment]
@ethanwharris I'm not a lawyer and this isn't legal advice. I think using YOLOv5 in IceVision makes it a derivative work, and IceVision therefore needs to be GPL-3.0 licensed too. If Flash uses IceVision it creates a derivative work again, which means Flash also needs to be distributed under the GPL-3.0 license. I'm not 100% sure that this is correct, but I wouldn't take the risk of integrating a GPL-3.0 licensed package, especially if I want companies to use my project.

Some relevant links:
* https://opensource.stackexchange.com/questions/1579/when-is-my-project-a-derivative-work-in-an-interpreted-language
* https://opensource.stackexchange.com/questions/2139/can-i-license-python-project-under-3-clause-bsd-while-it-has-gpl-based-dependenc
* https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l
* http://www.gnu.org/licenses/gpl-faq.html

**Comment by ethanwharris** [comment]
@juliangrosshauser Thanks for the links. As far as the YoloV5 founder is concerned, it seems that using the library in a or your own trained models with different licensing would be fine: https://github.com/ultralytics/yolov5/issues/967#issuecomment-692203992

**Comment by juliangrosshauser** [comment]
Quoting https://github.com/ultralytics/yolov5/issues/967#issuecomment-692203992:

> If you simply use this repo without altering it, you own any resulting products (i.e. trained models) and are free to assign them any license you wish as I understand it.

That's probably true for trained models, as long as you're not distributing the models (by providing a REST API for example). [AGPL](https://en.wikipedia.org/wiki/Affero_General_Public_License) closes this loophole. If you integrate the trained models into your mobile app for example, that you then distribute over app stores, you'd need to disclose the source code again though.

That said, all of that doesn't apply to integrating the package. Flash would still need to be licensed under GPL-3.0 as far as I understand. I might be wrong of course.

**Comment by zhiqwang** [comment]
Hi all here,

Do you plan to add a wrapper of https://github.com/Megvii-BaseDetection/YOLOX ?

**Comment by weiji14** [comment]
> Hi all here,
> 
> Do you plan to add a wrapper of https://github.com/Megvii-BaseDetection/YOLOX ?

I'm interested in this question as well :smile:. If my understanding is correct, the [IceVision](https://airctic.com/0.8.1/) integration PR at #608 will allow Pytorch Lightning to use all the Object Detection models listed by IceVision under https://github.com/airctic/icevision/tree/0.8.1/icevision/models. And since IceVision has integrations with [MMDetection](https://github.com/open-mmlab/mmdetection/tree/v2.15.1), that would include YOLOX (and all the other listed under https://github.com/open-mmlab/mmdetection/tree/v2.15.1#benchmark-and-model-zoo)? Is that correct?

**Comment by ethanwharris** [comment]
Hi @weiji14 @zhiqwang yes I think this is in the process of being added to icevision via mmdet. Once the models are in icevision we'll be able to add them into flash :smiley:
