### ISSUE TITLE
flash.image.SemanticSegmentationData dataloaders to convert greyscale/RGBA to RGB for train and val source images.

### ISSUE THREAD

**Issue by kurtjcu** [PyTorchLightning/lightning-flash#420]
## 🚀 Feature
Have The dataloaders convert any image type to rgb for use in segmentation.

### Motivation

greyscale or RGBA image types crash a training run

### Pitch

Most generic segmentation models work with RGB images [3 x length x width], some sources of images may contain either greyscale or RGBA image types. This simple modification would make the Flash segmentation more robust and easier to use. 

### Alternatives

Check image formats and give a clear error as to the the problem, current stack trace is not indicative of the problem.

**Comment by ethanwharris** [comment]
Hi @kurtjcu Thanks for the issue!

I think the problem is here: https://github.com/PyTorchLightning/lightning-flash/blob/113efabc3e28e80ef03f9b3ed92b11156a4a3ca5/flash/image/segmentation/data.py#L146
We should be loading the image with `torchvision.datasets.folder.default_loader` and then using `torchvision.transforms.ToTensor()` to convert it to a tensor. Those methods in torchvision will ensure that the final tensors always have three channels even if the image was greyscale.

Would you be interested in making a PR that implements this fix?
