### ISSUE TITLE
Installing [image] extras is not sufficient on Python 3.6?

### ISSUE THREAD

**Issue by brimoor** [PyTorchLightning/lightning-flash#451]
## 🐛 Bug

On Python 3.6, `pip install lightning-flash[image]` is not sufficient to allow me to use an `ObjectDetector`:

```py
from flash.image import ObjectDetector

# error: tells me I need to `pip install 'lightning-flash[image]'`, but I already did!
model = ObjectDetector.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/object_detection_model.pt")
```

I believe the issue is that pycocotools has a `python_version >= 3.7` marker in the [requirements file](https://github.com/PyTorchLightning/lightning-flash/blob/master/requirements/datatype_image.txt). Either that environment marker is necessary, in which case the image extras only support Python 3.7+, or the marker should be removed.

FWIW, I manually `pip install pycocotools` and was able to successfully use the checkpoint that I tried to load in the example code below.

### To Reproduce

Create a fresh environment:

```shell
conda create -n test python=3.6
conda activate test

pip install lightning-flash
pip install 'lightning-flash[image]'
```

Now try to use the image extras:

```py
from flash.image import ObjectDetector

# error: tells me I need to `pip install 'lightning-flash[image]'`, but I already did!
model = ObjectDetector.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/object_detection_model.pt")
```

### Environment

 - OS (e.g., Linux): macOS 10.14.6
 - Python version: Python 3.6.13 :: Anaconda, Inc.
 - Lightning Flash version: 0.4.0

**Comment by ethanwharris** [comment]
Hi @brimoor, thanks for bringing this to our attention. I can see that there was some discussion about it in the original PR here: https://github.com/PyTorchLightning/lightning-flash/pull/56/files#r571734084
@kaushikb11 Is there something we can put in the requirements so we can remove the Python 3.7 check?
Otherwise at the very least we can remove the check for coco from the check for `image` extras, but ideally this would just work as expected.
