### ISSUE TITLE
Data loader from dataframe

### ISSUE THREAD

**Issue by jorgeutd** [PyTorchLightning/lightning-flash#498]
## 🚀 Feature

Add support to Data loader from dataframe object in text classification tasks.

**Comment by ethanwharris** [comment]
Hi @jorgeutd thanks for the feature request. Would you be interested in trying to make a PR that adds this? If so, we can help you with next steps :smiley:

**Comment by jorgeutd** [comment]
Hi Ethan,

I can definitely take a crack at this during my weekends for sure. I would need to understand the process of course.

Thanks,

Jorge

**Comment by ethanwharris** [comment]
Hi @jorgeutd That would be awesome! Here are the steps I think you would need:

1. To add support for from_data_frame you would first need to create a TextDataFrameDataSource. This would be based on the other text data sources (like the TextFileDataSource here: https://github.com/PyTorchLightning/lightning-flash/blob/5d98cde907c148e5b8562d6e22dacd1dbd6c245a/flash/text/classification/data.py#L94) but load data from a dataframe instead.
2. You would then need to add a from_data_frame classmethod to the TextClassifcationData, based on the one that we have for TabularData here: https://github.com/PyTorchLightning/lightning-flash/blob/5d98cde907c148e5b8562d6e22dacd1dbd6c245a/flash/tabular/classification/data.py#L328

Let me know if there's anything that needs clarification. I've assigned you to the issue just so that we people can see who is working on it.

Thanks a lot :smiley:
