### ISSUE TITLE
[RFC] Default to `ApplyToKeys(INPUT)` if the provided transform is not already applied to keys.

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#645]
## 🚀 Feature

If an ApplyToKeys isn't used then we should just apply the provided transforms to the INPUT key. Some considerations / options:
- We could do this dynamically, try the transforms then if we get a type error or something we just wrap in an apply to keys, warn the user, and try again
- We could alternatively just document ApplyToKeys more prominently and give a meaningful error message that suggests using it when a typeerror or whatever is thrown

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @ethanwharris thank you for taking your time to open this issue. It would be nice to pass a function to extract the data from the batch, in the most vanilla scenario where we wish to return a x, y from the dataset the function will look like 

```python
lambda x: x[0], x[1]
```

Or we could create a custom transform, e.g. 

```python

class ToFlash:
    def __call__(self, x):
        return { 'input' : x[0], 'target' : x[1] }
```

and apply to a `Dataset`. To be honest, I prefer the first option since it allows more flexibility

Let me know your thoughts :)

**Comment by ethanwharris** [comment]
Re-opening this as the issue remains. Should be adressed as part of Data Pipeline V2 refactor.

**Comment by ethanwharris** [comment]
Closing this as no longer relevant. All custom transforms should be provided via an InputTransform class
