### ISSUE TITLE
Support cached models, tokenizers, etc. for HF tasks (particularly SpeechRecognition)

### ISSUE THREAD

**Issue by sl-93** [PyTorchLightning/lightning-flash#723]
I've tried to fine tune wav2vec model. and my model is created. but I can not use it offline. what should I do?

Thanks!

**Comment by ethanwharris** [comment]
Hi @sl-93 thanks for your question! Does it fail trying to load a model you previously trained or is it an issue with getting pretrained weights? Could you provide the error trace you get? We had an issue with image classifier backbones where checkpoints couldn't be loaded offline but where able to fix that one, so possibly a similar approach would work here. Thanks :smiley:

**Comment by sl-93** [comment]
@jonhare 
yes, the error is:
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

it seems i can not have the model locally and send request to load model.

**Comment by ethanwharris** [comment]
Hi @sl-93, I've looked in to this a bit and it seems there are a few places where HF requires internet connection to work. As a result, it's unfortunately not possible for us to support the speech recognition task without internet connection.

**Comment by sl-93** [comment]
> Hi @sl-93, I've looked in to this a bit and it seems there are a few places where HF requires internet connection to work. As a result, it's unfortunately not possible for us to support the speech recognition task without internet connection.

**Comment by sl-93** [comment]
@ethanwharris
so, what should I do in your idea? 
I tuned wav2vec model and when I want to load the tuned model, I get this error. 
how can I download the tuned model and use it offline?

**Comment by sl-93** [comment]
@ethanwharris
but when I load the model, it can work without internet connection.

**Comment by ethanwharris** [comment]
@sl-93 Yeah, the issue comes from huggingface loading the model, tokenizer, preprocessor ext. all from the web. So once the model has been loaded it would all work. It looks like there is support for users to manually save these files and then provide a path rather than just the model name. We could potentially support this through the backbone argument or through some sort of automated caching. Re-opening this issue to track that feature request. If you want to try to look into it that would be welcome :smiley: Hope that helps!
