### ISSUE TITLE
Preprocessing module is very confusing

### ISSUE THREAD

**Issue by dlangerm** [PyTorchLightning/lightning-flash#778]
## ❓ Questions and Help

There seems to be a bit of code smell cropping up with the #770  issue related to `to_onnx` and how example inputs are used. I have a few questions.

#### What is your question?

1. How does the DataPipeline class relate to the preprocess module? The documentation for this class is very sparse.
2. Why is it the responsibility of the Preprocessor to instantiate the data source when `from_data_source("something custom")` is called to create a data module? This flow is very unintuitive.
3. `ApplyToKeys` operates on dictionaries, and `example_input_array` can be a tensor, tuple, or dict. Where and how is this handled? For example in `to_onnx` or `summarize` the example_input_array tensor is passed through the model, which works fine on just the model, but the preprocessing expects a `dict` for the most part since it is highly encouraged in the docs to use that function as everything in flash is supposed to be a dict until right before inference. This results in all kinds of strange errors. 

#### Code

The fix for 3 seems to be to do this on my custom `Task`
```
    def _apply_batch_transfer_handler(self, batch: Any, device: Optional[torch.device] = None, dataloader_idx: Optional[int] = None) -> Any:
        if isinstance(batch, torch.Tensor):
            return super()._apply_batch_transfer_handler(batch={DefaultDataKeys.INPUT: batch}, device=device, dataloader_idx=dataloader_idx)[DefaultDataKeys.INPUT]
        else:
            return super()._apply_batch_transfer_handler(batch, device=device, dataloader_idx=dataloader_idx)
```

But I have no idea what kinds of side effects this would have and it feels like a strange fix to a fundamental problem.

#### What have you tried?

This issue sprang up when I implemented a custom preprocess class and spiraled from there. `to_onnx` and `summarize` (by extension, training) are broken due to this bug. The ImageClassificationPreprocess won't work for me because my outputs are continuous,

#### What's your environment?

 - OS: All
 - Packaging: conda/pip
 - Version lightning 1.4.7, flash 0.5.0, bolts 0.4.0

**Comment by aribornstein** [comment]
@tchaton

**Comment by tchaton** [comment]
Dear @dlangerm,

1. How does the DataPipeline class relate to the preprocess module? The documentation for this class is very sparse.

The DataPipeline object is used to connect the datamodule preprocess, data_source, deserializer with the model postprocess and serializer.
Futhermore, it is responsible to resolve the collate_fn injected within the DataLoader as collate_fn based on the hooks from the preprocess object. This is used to enable fine grained transforms. This is done there: https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/core/data/data_pipeline.py#L214


2. Why is it the responsibility of the Preprocessor to instantiate the data source when `from_data_source("something custom")` is called to create a data module? This flow is very unintuitive.

You are entirely right. This is legacy and we plan to refactor it.
The preprocess was introduced first while design

I would prefer the DataSource to own the preprocess objects but there were some hicks while doing so and enabling model.predict to work together. I need to re-investigate this.


3. `ApplyToKeys` operates on dictionaries, and `example_input_array` can be a tensor, tuple, or dict. Where and how is this handled? For example in `to_onnx` or `summarize` the example_input_array tensor is passed through the model, which works fine on just the model, but the preprocessing expects a `dict` for the most part since it is highly encouraged in the docs to use that function as everything in flash is supposed to be a dict until right before inference. This results in all kinds of strange errors. 

This is a great remark and I don't believe we support this properly right now. `example_input_array` should be a dictionary.

If you are interested, ping me on Slack and we could organize a quick chat for me to answer your questions and explain you deeper part of the DataPipeline.

Best,
T.C

**Comment by tchaton** [comment]
Dear @dlangerm,

I have been working on some ideas: https://github.com/PyTorchLightning/lightning-flash/pull/815.

Mind giving me your opinion ?

Best,
T.C

**Comment by dlangerm** [comment]
@tchaton 

So from my investigations, it looks like a lot of the artificial coupling is due to the Preprocessor and DataModule all keeping track of their various data sources and having `Preprocessor.data_source_of_name` function.

What if there were a DataSource registry where we could call `data_source_of_name` instead of on the preprocessor? That way if a data source wanted to register itself as existing it could just register with the registry upon instantiation, which would, in turn, provide the information necessary to decouple the preprocessor from the data source.

**Comment by tchaton** [comment]
> @tchaton
> 
> So from my investigations, it looks like a lot of the artificial coupling is due to the Preprocessor and DataModule all keeping track of their various data sources and having `Preprocessor.data_source_of_name` function.
> 
> What if there were a DataSource registry where we could call `data_source_of_name` instead of on the preprocessor? That way if a data source wanted to register itself as existing it could just register with the registry upon instantiation, which would, in turn, provide the information necessary to decouple the preprocessor from the data source.

Let me replace it by a registry.

**Comment by dlangerm** [comment]
@tchaton Check out my PR, I started the work but admittedly I'm unfamiliar with registries. It wasn't much of a change though

**Comment by dlangerm** [comment]
#816
