### ISSUE TITLE
Correct way to bring my data for object detection

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [PyTorchLightning/lightning-flash#827]
Hi guys,

I hope you are doing great. Currently, flash support only voc/coco datasets for object detection

```python
datamodule = ObjectDetectionData.from_coco(
    train_folder="data/coco128/images/train2017/",
    train_ann_file="data/coco128/annotations/instances_train2017.json",
    val_split=0.1,
    image_size=128,
)
```
What if I have my own dataset and I just want to bring it into? I only need to tell it you how to get an image and a label? Maybe I can subclass something and overwrite the correct methods or pass my own strategy. Is there a specific reason I am missing to not make the data pipeline extensible/composable? Thank you.

Cheers, 

Francesco

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini Since we now have integration with IceVision, one option here is to create an icevision style parser and use it with the `from_folders` method. For example, in the [instance segmentation example](https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/instance_segmentation.py#L27) we use the pets data set from the icedata repo, which has it's own parser. Code for multiple custom object detection formats can be found in the [icedata repo](https://github.com/airctic/icedata/tree/master/icedata/datasets).

Regarding making this extensible / composable on the Flash side, that's definitely something we'd like to have. There is some ongoing work to make that cleaner / better in #821 please feel free to take a look at it and leave your thoughts :smiley:

**Comment by FrancescoSaverioZuppichini** [comment]
@ethanwharris got it! This is identical to the issue for image classification. People cannot use their data! Are you sure there is not a way to create a `DataModule` that returns the correct data points in order to use flash in a real case scenario? Otherwise, I fear I'll have to write an adapter that formats my dataset into coco. It seems a little crazy to me that flash cannot be used in a custom real-case scenario, but probably I am missing something here. 

It would be very easy to do so, just make a `ObjectDetectionDataset` that we can subclass with a function to return the image and a function to return the target, e.g. `get_image`, `get_target`, then we can easily create our `DataModule`. Let me know your thoughts :)
