### ISSUE TITLE
MasksRecordComponent does not exist in icevision

### ISSUE THREAD

**Issue by aisensiy** [PyTorchLightning/lightning-flash#877]
This line: 

https://github.com/PyTorchLightning/lightning-flash/blob/4f608b0b53a9b7004a71a6c0bcc4195ca4644008/flash/core/integrations/icevision/transforms.py#L34

is commented in:

https://github.com/airctic/icevision/blob/e5503f7fc7d0548dbc222494e436998aab4145e0/icevision/core/record_components.py#L453

**Comment by ethanwharris** [comment]
Hi @aisensiy thanks for reporting this. As IceVision is an unstable API I think we may need to pin our requirements to only support a specific version. It looks like they will make a release soon so maybe after that we should update and drop support for older versions. We could also perhaps add some testing with IceVision master so that we avoid bugs like this in future. What do you think? Interested to hear your thoughts :smiley:
