### ISSUE TITLE
import flash not working in kaggle

### ISSUE THREAD

**Issue by ramkirank** [PyTorchLightning/lightning-flash#904]
## 🐛 Bug

Not able to use flash after installing via pip in kaggle notebook. I want to use InstanceSegmentation model so i need to use image dependencies . This problem occurs in  gpu and cpu-only notebooks of kaggle.

### To Reproduce
1. Go to kaggle notebook
2. Run !pip install 'icevision' 'lightning-flash[image]'
3. Run import flash
that gives following error:
ImportError: /opt/conda/lib/python3.7/site-packages/torchtext/_torchtext.so: undefined symbol: _ZN2at6detail10noopDeleteEPv

notebook can be viewed at https://www.kaggle.com/ramkirank/flash/

**Comment by ethanwharris** [comment]
Hi @ramkirank, thanks for reporting this. This issue happens when a different version of torch is installed in an environment that already has torchtext installed. Since we don't need torchtext for Flash, you could try:
```
!pip uninstall torchtext
!pip install 'icevision' 'lightning-flash[image]'
```
This has worked for similar issues we've had on colab in the past. Hope that helps :smiley:

**Comment by ramkirank** [comment]
Thanks. problem is solved .i have to use -y for pip because i am using this in a notebook cell. 
!pip uninstall -y torchtext
!pip install 'icevision' 'lightning-flash[image]'
