### ISSUE TITLE
text classify prediction - memory overflow

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/lightning-flash#983]
## 🐛 Bug

seems like the prediction does not honor batch size and tries to load all at once...
Have this simple prediction with `backbone="xlm-roberta-base"` and running predictions on https://www.kaggle.com/c/jigsaw-toxic-severity-rating/data?select=comments_to_score.csv
```py
predictions = model.predict(df_comments["text"])
```
crashes on Kaggle kernel, but if I take it with batch size it works fine (just very slow)
```py
predictions = []
for i in range(int(len(df_comments) / datamodule.batch_size)):
    predictions += model.predict(df_comments["text"][i * datamodule.batch_size:(i + 1) * datamodule.batch_size])
```

### To Reproduce

https://www.kaggle.com/jirkaborovec/toxic-comments-with-lightning-flash?scriptVersionId=80223034

### Additional context

cc: @karthikrangasai @rohitgr7

**Comment by rohitgr7** [comment]
from what I understand from the codebase is that internally it stacks up all the data in a single tensor and passes it through `predict_step`. So when you pass the whole column, it will do a forward on the complete stacked tensor. But when you send the part of the dataset then it will only store part of the sliced dataset and predict on a sample with less overhead on the device. And the reason for the second one being slow is that it will use for-loops and thus reduce vectorization, which might slow down the process.

I wonder why `model.predict` doesn't support a dataloader as an input.

**Comment by ethanwharris** [comment]
Hi @Borda @rohitgr7 the reason for the way `model.predict` is designed is that we expect it only to be used for getting predictions from a few samples. For more complex use cases (e.g. a dataloader), we would recommend using `flash.Trainer.predict` instead (which would then load batches etc correctly). I think this is something we could look at changing though, it seems weird to me that `model.predict` doesn't just create a trainer internally. Ideally there would be just one way to make predictions rather than two...

**Comment by ethanwharris** [comment]
Closing this as we now only support `Trainer.predict` where this issue is not encountered.
